#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-paradise
Version  : 2.1.0.2.11.11
Release  : 2
URL      : https://github.com/scalamacros/paradise/archive/v2.1.0_2.11.11.tar.gz
Source0  : https://github.com/scalamacros/paradise/archive/v2.1.0_2.11.11.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.pom
Source3  : https://repo1.maven.org/maven2/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.jar
Source4  : https://repo1.maven.org/maven2/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-paradise-data = %{version}-%{release}
Requires: mvn-paradise-license = %{version}-%{release}

%description
## Macro Paradise Plugin
[![Join the chat at https://gitter.im/scalamacros/paradise](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/scalamacros/paradise?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%package data
Summary: data components for the mvn-paradise package.
Group: Data

%description data
data components for the mvn-paradise package.


%package license
Summary: license components for the mvn-paradise package.
Group: Default

%description license
license components for the mvn-paradise package.


%prep
%setup -q -n paradise-2.1.0_2.11.11

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-paradise
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-paradise/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.jar
/usr/share/java/.m2/repository/org/scalamacros/paradise_2.11.12/2.1.0/paradise_2.11.12-2.1.0.pom
/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.jar
/usr/share/java/.m2/repository/org/scalamacros/paradise_2.12.7/2.1.0/paradise_2.12.7-2.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-paradise/LICENSE.md
